export const PRODUCT_BADGE_KEYS = [
  // Warranty
  'pdpWarrantyTitle',
  'pdpWarrantySubtitle',
  // Delivery
  'pdpDeliveryTitle',
  'pdpDeliverySubtitle',
  // Returns
  'pdpReturnsTitle',
  'pdpReturnsSubtitle',
  // Cutoff hour (e.g. "18" for 18:00)
  'pdpCutoffHour',
  // Delivery timing rules
  'pdpDeliveryMinsk',
  'pdpDeliveryBelarusRegion',
  'pdpDeliveryChinaLocal',
  'pdpDeliveryChinaNationwide',
  'pdpAirFreightDays',
  'pdpRailFreightDays',
  'pdpSeaFreightDays',
  // Trust Badges (Mobile & Desktop)
  'pdpFactoryTitle',
  'pdpFactoryDesc',
  'pdpQcTitle',
  'pdpQcDesc',
  'pdpLogisticsTitle',
  'pdpLogisticsDesc',
  'pdpEscrowTitle',
  'pdpEscrowDesc',
  // Buyer Q&A / FAQ
  'pdpFaqTitle',
  'pdpFaqSubtitle',
  'pdpFaqAskBtn',
  'pdpFaq1Q',
  'pdpFaq1A',
  'pdpFaq2Q',
  'pdpFaq2A',
  'pdpFaq3Q',
  'pdpFaq3A',
  'pdpFaq4Q',
  'pdpFaq4A',
  'pdpFaq5Q',
  'pdpFaq5A',
] as const;

export type ProductBadgeKey = (typeof PRODUCT_BADGE_KEYS)[number];

export const DEFAULT_PRODUCT_BADGES: Record<'en' | 'ru' | 'zh', Record<ProductBadgeKey, string>> = {
  en: {
    pdpWarrantyTitle: '2-Year Warranty',
    pdpWarrantySubtitle: 'Full factory coverage',
    pdpDeliveryTitle: 'Express Delivery',
    pdpDeliverySubtitle: 'Free over $50+',
    pdpReturnsTitle: '14-Day Returns',
    pdpReturnsSubtitle: 'Hassle-free guarantee',
    pdpCutoffHour: '18',
    pdpDeliveryMinsk: 'Tomorrow (1 business day)',
    pdpDeliveryBelarusRegion: '1 – 3 business days',
    pdpDeliveryChinaLocal: '24 – 48 hours',
    pdpDeliveryChinaNationwide: '2 – 3 days',
    pdpAirFreightDays: '5 – 8 business days',
    pdpRailFreightDays: '14 – 20 business days',
    pdpSeaFreightDays: '20 – 35 days',
    pdpFactoryTitle: 'Direct Verified Factory',
    pdpFactoryDesc: 'Zero middleman markup directly from manufacturer',
    pdpQcTitle: 'Rigorous Quality Inspection',
    pdpQcDesc: 'Full physical check before shipment',
    pdpLogisticsTitle: 'Door-to-Door Logistics',
    pdpLogisticsDesc: 'Air, rail & sea freight with customs clearance',
    pdpEscrowTitle: 'Trade Assurance Escrow',
    pdpEscrowDesc: 'Funds protected until inspection passes',
    pdpFaqTitle: 'Frequently Asked Questions',
    pdpFaqSubtitle: 'Get quick answers to common questions',
    pdpFaqAskBtn: 'Ask a Question',
    pdpFaq1Q: 'What is the minimum order quantity?',
    pdpFaq1A: 'The minimum order quantity for this product is {moq} units. Wholesale pricing is available for larger orders.',
    pdpFaq2Q: 'What is the shipping time?',
    pdpFaq2A: 'Standard shipping takes 7-14 business days. Express door-to-door shipping options are available at checkout.',
    pdpFaq3Q: 'Do you offer bulk wholesale discounts?',
    pdpFaq3A: 'Yes! We offer tiered wholesale pricing for bulk orders. Contact our trade managers for custom container rates.',
    pdpFaq4Q: 'What is your return & inspection policy?',
    pdpFaq4A: 'We offer full pre-shipment quality inspection and 30-day return coverage for any verified manufacturing defects.',
    pdpFaq5Q: 'Can I customize this product or add my logo (OEM/ODM)?',
    pdpFaq5A: 'Yes, OEM packaging, custom branding, and ODM tooling are supported for volume orders. Contact sourcing for specs.',
  },
  ru: {
    pdpWarrantyTitle: '2 года гарантии',
    pdpWarrantySubtitle: 'Официальная заводская гарантия',
    pdpDeliveryTitle: 'Экспресс-доставка',
    pdpDeliverySubtitle: 'От $50 бесплатно',
    pdpReturnsTitle: '14 дней возврат',
    pdpReturnsSubtitle: 'Легкий и быстрый возврат',
    pdpCutoffHour: '18',
    pdpDeliveryMinsk: 'Завтра (1 рабочий день)',
    pdpDeliveryBelarusRegion: '1 – 3 рабочих дня',
    pdpDeliveryChinaLocal: '24 – 48 часов',
    pdpDeliveryChinaNationwide: '2 – 3 дня',
    pdpAirFreightDays: '5 – 8 рабочих дней',
    pdpRailFreightDays: '14 – 20 рабочих дней',
    pdpSeaFreightDays: '20 – 35 дней',
    pdpFactoryTitle: 'Прямой производитель',
    pdpFactoryDesc: 'Без наценок посредников напрямую с завода',
    pdpQcTitle: 'Контроль качества (QC)',
    pdpQcDesc: 'Проверка товара перед отправкой',
    pdpLogisticsTitle: 'Таможенная очистка DDP',
    pdpLogisticsDesc: 'Авиа, ж/д и морская доставка до двери',
    pdpEscrowTitle: 'Безопасная сделка',
    pdpEscrowDesc: 'Оплата защищена до получения и проверки',
    pdpFaqTitle: 'Часто задаваемые вопросы',
    pdpFaqSubtitle: 'Быстрые ответы на распространённые вопросы покупателей',
    pdpFaqAskBtn: 'Задать вопрос',
    pdpFaq1Q: 'Каков минимальный объём заказа (MOQ)?',
    pdpFaq1A: 'Минимальный заказ для этого товара — {moq} шт. Для крупных партий действуют специальные оптовые цены.',
    pdpFaq2Q: 'Каковы сроки доставки и таможни?',
    pdpFaq2A: 'Авиа доставка занимает 5–8 дней, ж/д экспресс 14–20 дней. Предоставляется доставка с полной таможенной очисткой.',
    pdpFaq3Q: 'Предоставляете ли вы оптовые скидки на объем?',
    pdpFaq3A: 'Да! Мы предлагаем прогрессивную шкалу скидок для оптовых заказов. Свяжитесь с нами для точного расчета партии.',
    pdpFaq4Q: 'Каковы условия гарантии и возврата?',
    pdpFaq4A: 'Все товары проходят проверку качества перед отправкой. Действует 30-дневная гарантия на заводские дефекты.',
    pdpFaq5Q: 'Возможно ли брендирование и производство под заказ (OEM/ODM)?',
    pdpFaq5A: 'Да, нанесение логотипа и индивидуальная упаковка доступны для партий от 500 шт. Напишите нам детали заказа.',
  },
  zh: {
    pdpWarrantyTitle: '2年原厂质保',
    pdpWarrantySubtitle: '官方正品全国联保',
    pdpDeliveryTitle: '极速直达物流',
    pdpDeliverySubtitle: '满额免费包邮',
    pdpReturnsTitle: '14天无忧退换',
    pdpReturnsSubtitle: '支持极速退款换货',
    pdpCutoffHour: '18',
    pdpDeliveryMinsk: '次日达（明斯克专线1个工作日）',
    pdpDeliveryBelarusRegion: '白俄罗斯各州（1 – 3个工作日）',
    pdpDeliveryChinaLocal: '中国核心仓现货（24 – 48小时）',
    pdpDeliveryChinaNationwide: '中国全国陆运（2 – 3天）',
    pdpAirFreightDays: '5 – 8个工作日（空运专线含税到门）',
    pdpRailFreightDays: '14 – 20个工作日（中欧班列铁路集运）',
    pdpSeaFreightDays: '20 – 35天（国际海运整柜/拼箱）',
    pdpFactoryTitle: '源头工厂直供',
    pdpFactoryDesc: '无中间商一手出厂底价',
    pdpQcTitle: '专业验厂与品控',
    pdpQcDesc: '出货前实物检测严格把关',
    pdpLogisticsTitle: '双清包税物流专线',
    pdpLogisticsDesc: '海运空运铁路全链路门到门',
    pdpEscrowTitle: '贸易资金担保',
    pdpEscrowDesc: '验货通过后支付尾款安全有保障',
    pdpFaqTitle: '买家常见问答 / FAQ',
    pdpFaqSubtitle: '关于起订量、物流运输、定制和质保的常见疑问解答',
    pdpFaqAskBtn: '在线咨询 / 提问',
    pdpFaq1Q: '本商品的最小起订量（MOQ）是多少？',
    pdpFaq1A: '该商品最小起订量为 {moq} 件。批量采购可享阶梯批发底价。',
    pdpFaq2Q: '国际运输需要多长时间？',
    pdpFaq2A: '空运双清包税专线 5–8 个工作日，中欧班列铁路集运 14–20 个工作日，海运 20–35 天。',
    pdpFaq3Q: '大批量采购有阶梯折扣吗？',
    pdpFaq3A: '支持整柜及大批量批发折扣！我们的贸易经理可为您提供实时离岸价（FOB）或到门包税价（DDP）。',
    pdpFaq4Q: '售后退换与质检保障政策是怎样的？',
    pdpFaq4A: '出货前由专业质检团队进行实物验货并提供检测报告；正品质量问题享受全面售后保障。',
    pdpFaq5Q: '是否支持贴牌定制与打样（OEM / ODM）？',
    pdpFaq5A: '支持定制包装、印刷 Logo 和模具开发。订单量达到定制门槛即可联系客服沟通打样与生产周期。',
  },
};
