export const PRODUCT_BADGE_KEYS = [
  // Warranty
  'pdpWarrantyTitle',
  'pdpWarrantySubtitle',
  // Delivery
  'pdpDeliveryTitle',
  'pdpDeliverySubtitle',
  // Returns
  'pdpReturnsTitle',
  'pdpReturnsSubtitle',
  // Cutoff hour (e.g. "18" for 18:00)
  'pdpCutoffHour',
  // Delivery timing rules
  'pdpDeliveryMinsk',
  'pdpDeliveryBelarusRegion',
  'pdpDeliveryChinaLocal',
  'pdpDeliveryChinaNationwide',
  'pdpAirFreightDays',
  'pdpRailFreightDays',
  'pdpSeaFreightDays',
  // Trust Badges (Mobile & Desktop)
  'pdpFactoryTitle',
  'pdpFactoryDesc',
  'pdpQcTitle',
  'pdpQcDesc',
  'pdpLogisticsTitle',
  'pdpLogisticsDesc',
  'pdpEscrowTitle',
  'pdpEscrowDesc',
] as const;

export type ProductBadgeKey = (typeof PRODUCT_BADGE_KEYS)[number];

export const DEFAULT_PRODUCT_BADGES: Record<'en' | 'ru' | 'zh', Record<ProductBadgeKey, string>> = {
  en: {
    pdpWarrantyTitle: '2-Year Warranty',
    pdpWarrantySubtitle: 'Full factory coverage',
    pdpDeliveryTitle: 'Express Delivery',
    pdpDeliverySubtitle: 'Free over $50+',
    pdpReturnsTitle: '14-Day Returns',
    pdpReturnsSubtitle: 'Hassle-free guarantee',
    pdpCutoffHour: '18',
    pdpDeliveryMinsk: 'Tomorrow (1 business day)',
    pdpDeliveryBelarusRegion: '1 – 3 business days',
    pdpDeliveryChinaLocal: '24 – 48 hours',
    pdpDeliveryChinaNationwide: '2 – 3 days',
    pdpAirFreightDays: '5 – 8 business days',
    pdpRailFreightDays: '14 – 20 business days',
    pdpSeaFreightDays: '20 – 35 days',
    pdpFactoryTitle: 'Direct Verified Factory',
    pdpFactoryDesc: 'Zero middleman markup directly from manufacturer',
    pdpQcTitle: 'Rigorous Quality Inspection',
    pdpQcDesc: 'Full physical check before shipment',
    pdpLogisticsTitle: 'Door-to-Door Logistics',
    pdpLogisticsDesc: 'Air, rail & sea freight with customs clearance',
    pdpEscrowTitle: 'Trade Assurance Escrow',
    pdpEscrowDesc: 'Funds protected until inspection passes',
  },
  ru: {
    pdpWarrantyTitle: '2 года гарантии',
    pdpWarrantySubtitle: 'Официальная заводская гарантия',
    pdpDeliveryTitle: 'Экспресс-доставка',
    pdpDeliverySubtitle: 'От $50 бесплатно',
    pdpReturnsTitle: '14 дней возврат',
    pdpReturnsSubtitle: 'Легкий и быстрый возврат',
    pdpCutoffHour: '18',
    pdpDeliveryMinsk: 'Завтра (1 рабочий день)',
    pdpDeliveryBelarusRegion: '1 – 3 рабочих дня',
    pdpDeliveryChinaLocal: '24 – 48 часов',
    pdpDeliveryChinaNationwide: '2 – 3 дня',
    pdpAirFreightDays: '5 – 8 рабочих дней',
    pdpRailFreightDays: '14 – 20 рабочих дней',
    pdpSeaFreightDays: '20 – 35 дней',
    pdpFactoryTitle: 'Прямой производитель',
    pdpFactoryDesc: 'Без наценок посредников напрямую с завода',
    pdpQcTitle: 'Контроль качества (QC)',
    pdpQcDesc: 'Проверка товара перед отправкой',
    pdpLogisticsTitle: 'Таможенная очистка DDP',
    pdpLogisticsDesc: 'Авиа, ж/д и морская доставка до двери',
    pdpEscrowTitle: 'Безопасная сделка',
    pdpEscrowDesc: 'Оплата защищена до получения и проверки',
  },
  zh: {
    pdpWarrantyTitle: '2年原厂质保',
    pdpWarrantySubtitle: '官方正品全国联保',
    pdpDeliveryTitle: '极速直达物流',
    pdpDeliverySubtitle: '满额免费包邮',
    pdpReturnsTitle: '14天无忧退换',
    pdpReturnsSubtitle: '支持极速退款换货',
    pdpCutoffHour: '18',
    pdpDeliveryMinsk: '次日达（明斯克专线1个工作日）',
    pdpDeliveryBelarusRegion: '白俄罗斯各州（1 – 3个工作日）',
    pdpDeliveryChinaLocal: '中国核心仓现货（24 – 48小时）',
    pdpDeliveryChinaNationwide: '中国全国陆运（2 – 3天）',
    pdpAirFreightDays: '5 – 8个工作日（空运专线含税到门）',
    pdpRailFreightDays: '14 – 20个工作日（中欧班列铁路集运）',
    pdpSeaFreightDays: '20 – 35天（国际海运整柜/拼箱）',
    pdpFactoryTitle: '源头工厂直供',
    pdpFactoryDesc: '无中间商一手出厂底价',
    pdpQcTitle: '专业验厂与品控',
    pdpQcDesc: '出货前实物检测严格把关',
    pdpLogisticsTitle: '双清包税物流专线',
    pdpLogisticsDesc: '海运空运铁路全链路门到门',
    pdpEscrowTitle: '贸易资金担保',
    pdpEscrowDesc: '验货通过后支付尾款安全有保障',
  },
};
