export const heroBanners = [
  {
    id: 'hero-1',
    title: 'Premium Kitchenware from Yiwu, China',
    subtitle: 'Global Trade Solutions for International Buyers',
    ctaText: 'Shop Now',
    ctaLink: '/products',
    secondaryCtaText: 'View Categories',
    secondaryCtaLink: '/products',
    imageUrl: '/images/hero/hero-1.jpg',
    imageAlt: 'Premium kitchenware display',
    position: 'center',
    bgColor: '#1a3a5c',
    textColor: '#ffffff',
    order: 1,
    isActive: true,
  },
  {
    id: 'hero-2',
    title: 'Wholesale Prices for Bulk Orders',
    subtitle: 'Custom sourcing and logistics from Yiwu to your door',
    ctaText: 'Request Quote',
    ctaLink: '/wholesale',
    secondaryCtaText: 'Learn More',
    secondaryCtaLink: '/services',
    imageUrl: '/images/hero/hero-2.jpg',
    imageAlt: 'Wholesale kitchenware in bulk',
    position: 'center',
    bgColor: '#1a1a2e',
    textColor: '#ffffff',
    order: 2,
    isActive: true,
  },
  {
    id: 'hero-3',
    title: 'Export-Ready Kitchenware',
    subtitle: 'HS Code compliance • Customs support • Global shipping',
    ctaText: 'Explore Products',
    ctaLink: '/products',
    secondaryCtaText: 'Our Services',
    secondaryCtaLink: '/services',
    imageUrl: '/images/hero/hero-3.jpg',
    imageAlt: 'Export ready kitchenware',
    position: 'center',
    bgColor: '#2c3e50',
    textColor: '#ffffff',
    order: 3,
    isActive: true,
  },
]
