export const sampleProducts = [
  // Cookware - Stainless Steel
  {
    name: 'Stainless Steel Frying Pan 10"',
    slug: 'stainless-steel-frying-pan-10',
    description: 'Premium stainless steel construction with encapsulated base for even heating. Dishwasher safe. Compatible with all cooktops including induction. Ergonomic handle stays cool during cooking.',
    categorySlug: 'stainless-steel-cookware',
    price: 24.99,
    comparePrice: 34.99,
    costPrice: 14.99,
    stock: 150,
    sku: 'YW-SS-FP10',
    hsCode: '7323.93.0000',
    weightKg: 1.2,
    material: 'Stainless Steel',
    brand: 'YIWU',
    isFeatured: true,
  },
  {
    name: 'Stainless Steel Sauce Pan 2qt',
    slug: 'stainless-steel-sauce-pan-2qt',
    description: 'Professional-grade sauce pan with triple-layered bottom for superior heat distribution. Mirror-polished finish. Includes tempered glass lid with steam vent.',
    categorySlug: 'sauce-pans',
    price: 29.99,
    comparePrice: 39.99,
    costPrice: 17.99,
    stock: 120,
    sku: 'YW-SS-SP2',
    hsCode: '7323.93.0000',
    weightKg: 1.5,
    material: 'Stainless Steel',
    brand: 'ChefPro',
    isFeatured: true,
  },
  {
    name: 'Stainless Steel Stock Pot 8qt',
    slug: 'stainless-steel-stock-pot-8qt',
    description: 'Large capacity stock pot perfect for soups, stews, and pasta. Heavy-duty construction with riveted handles. Induction compatible.',
    categorySlug: 'stock-pots',
    price: 49.99,
    comparePrice: 69.99,
    costPrice: 29.99,
    stock: 80,
    sku: 'YW-SS-SP8',
    hsCode: '7323.93.0000',
    weightKg: 2.8,
    material: 'Stainless Steel',
    brand: 'KitchenMaster',
  },
  
  // Cookware - Non-stick
  {
    name: 'Non-Stick Frying Pan 8"',
    slug: 'non-stick-frying-pan-8',
    description: 'PFOA-free non-stick coating for healthy cooking. Lightweight aluminum construction. Heat-resistant silicone handle. Easy to clean.',
    categorySlug: 'non-stick-cookware',
    price: 15.99,
    comparePrice: 22.99,
    costPrice: 9.59,
    stock: 200,
    sku: 'YW-NS-FP8',
    hsCode: '7615.10.0000',
    weightKg: 0.8,
    material: 'Aluminum',
    brand: 'YIWU',
    isFeatured: true,
  },
  {
    name: 'Non-Stick Frying Pan 12"',
    slug: 'non-stick-frying-pan-12',
    description: 'Large non-stick frying pan ideal for family meals. 3-layer non-stick coating. Suitable for all cooktops except induction.',
    categorySlug: 'non-stick-cookware',
    price: 21.99,
    comparePrice: 29.99,
    costPrice: 13.19,
    stock: 180,
    sku: 'YW-NS-FP12',
    hsCode: '7615.10.0000',
    weightKg: 1.1,
    material: 'Aluminum',
    brand: 'ProCook',
  },

  // Cookware - Cast Iron
  {
    name: 'Cast Iron Skillet 12"',
    slug: 'cast-iron-skillet-12',
    description: 'Pre-seasoned cast iron skillet. Excellent heat retention and even cooking. Versatile for stovetop, oven, grill, and campfire. Hand wash only.',
    categorySlug: 'cast-iron-cookware',
    price: 32.99,
    comparePrice: 44.99,
    costPrice: 19.79,
    stock: 90,
    sku: 'YW-CI-SK12',
    hsCode: '7323.94.0000',
    weightKg: 3.5,
    material: 'Cast Iron',
    brand: 'EliteHome',
    isFeatured: true,
  },
  {
    name: 'Cast Iron Dutch Oven 5qt',
    slug: 'cast-iron-dutch-oven-5qt',
    description: 'Traditional Dutch oven perfect for slow-cooking, braising, and baking. Pre-seasoned. Includes tight-fitting lid.',
    categorySlug: 'cast-iron-dutch-ovens',
    price: 54.99,
    comparePrice: 74.99,
    costPrice: 32.99,
    stock: 60,
    sku: 'YW-CI-DO5',
    hsCode: '7323.94.0000',
    weightKg: 5.2,
    material: 'Cast Iron',
    brand: 'ChefPro',
  },

  // Bakeware
  {
    name: 'Baking Sheet Set 3-Piece',
    slug: 'baking-sheet-set-3-piece',
    description: 'Commercial-grade baking sheets in 3 sizes. Heavy-duty construction. Non-stick coating. Dishwasher safe. Includes small, medium, and large sheets.',
    categorySlug: 'baking-trays-sheets',
    price: 34.99,
    comparePrice: 49.99,
    costPrice: 20.99,
    stock: 110,
    sku: 'YW-BW-BS3',
    hsCode: '7615.10.0000',
    weightKg: 2.1,
    material: 'Aluminum',
    brand: 'YIWU',
    isFeatured: true,
  },
  {
    name: 'Non-Stick Muffin Pan 12-Cup',
    slug: 'non-stick-muffin-pan-12-cup',
    description: 'Standard 12-cup muffin pan with premium non-stick coating. Even heat distribution. Easy release. Perfect for muffins, cupcakes, and more.',
    categorySlug: 'muffin-cupcake-pans',
    price: 16.99,
    comparePrice: 24.99,
    costPrice: 10.19,
    stock: 140,
    sku: 'YW-BW-MP12',
    hsCode: '7615.10.0000',
    weightKg: 0.9,
    material: 'Aluminum',
    brand: 'KitchenMaster',
  },
  {
    name: 'Round Cake Pan 9" Set of 2',
    slug: 'round-cake-pan-9-set-of-2',
    description: 'Professional cake pans with removable bottoms. Non-stick coating for easy release. Perfect for layered cakes and cheesecakes. Set of 2.',
    categorySlug: 'cake-pans',
    price: 22.99,
    comparePrice: 32.99,
    costPrice: 13.79,
    stock: 95,
    sku: 'YW-BW-CP9',
    hsCode: '7615.10.0000',
    weightKg: 1.4,
    material: 'Aluminum',
    brand: 'ProCook',
  },

  // Kitchen Utensils
  {
    name: 'Silicone Spatula Set 4-Piece',
    slug: 'silicone-spatula-set-4-piece',
    description: 'Heat-resistant silicone spatulas. Wooden handles. Non-scratch. Dishwasher safe. Set includes turner, spoon, slotted spoon, and ladle.',
    categorySlug: 'spatulas-turners',
    price: 18.99,
    comparePrice: 26.99,
    costPrice: 11.39,
    stock: 170,
    sku: 'YW-UT-SS4',
    hsCode: '8215.99.0000',
    weightKg: 0.4,
    material: 'Silicone',
    brand: 'YIWU',
    isFeatured: true,
  },
  {
    name: 'Stainless Steel Whisk 10"',
    slug: 'stainless-steel-whisk-10',
    description: 'Professional balloon whisk. Heavy-duty stainless steel wires. Comfortable ergonomic handle. Perfect for whipping cream and mixing batters.',
    categorySlug: 'whisks-mixers',
    price: 12.99,
    comparePrice: 17.99,
    costPrice: 7.79,
    stock: 200,
    sku: 'YW-UT-WH10',
    hsCode: '8215.99.0000',
    weightKg: 0.3,
    material: 'Stainless Steel',
    brand: 'ChefPro',
  },
  {
    name: 'Measuring Cup Set 4-Piece',
    slug: 'measuring-cup-set-4-piece',
    description: 'Stainless steel measuring cups. Engraved measurements. Includes 1 cup, 1/2 cup, 1/3 cup, and 1/4 cup. Ring for easy storage.',
    categorySlug: 'measuring-cups-spoons',
    price: 14.99,
    comparePrice: 19.99,
    costPrice: 8.99,
    stock: 150,
    sku: 'YW-UT-MC4',
    hsCode: '8215.99.0000',
    weightKg: 0.5,
    material: 'Stainless Steel',
    brand: 'KitchenMaster',
  },

  // Kitchen Appliances
  {
    name: 'Electric Kettle 1.7L Stainless Steel',
    slug: 'electric-kettle-1-7l-stainless-steel',
    description: 'Fast-boiling electric kettle. 1500W power. Auto shut-off and boil-dry protection. Cordless design. LED indicator light.',
    categorySlug: 'electric-kettles',
    price: 39.99,
    comparePrice: 54.99,
    costPrice: 23.99,
    stock: 75,
    sku: 'YW-AP-EK17',
    hsCode: '8516.79.0000',
    weightKg: 1.8,
    material: 'Stainless Steel',
    brand: 'YIWU',
    isFeatured: true,
  },
  {
    name: 'Drip Coffee Maker 12-Cup',
    slug: 'drip-coffee-maker-12-cup',
    description: 'Programmable coffee maker with 24-hour timer. Keep warm function. Reusable filter. Glass carafe. Automatic shut-off after 2 hours.',
    categorySlug: 'coffee-makers',
    price: 49.99,
    comparePrice: 69.99,
    costPrice: 29.99,
    stock: 60,
    sku: 'YW-AP-CM12',
    hsCode: '8516.71.0000',
    weightKg: 2.3,
    material: 'Plastic',
    brand: 'EliteHome',
  },
  {
    name: 'Immersion Blender 500W',
    slug: 'immersion-blender-500w',
    description: 'Powerful hand blender with variable speed control. Stainless steel blades. Includes whisk and chopper attachments. Ergonomic grip.',
    categorySlug: 'blenders-mixers',
    price: 34.99,
    comparePrice: 49.99,
    costPrice: 20.99,
    stock: 85,
    sku: 'YW-AP-IB500',
    hsCode: '8509.40.0000',
    weightKg: 1.2,
    material: 'Stainless Steel',
    brand: 'ProCook',
  },

  // Tableware
  {
    name: 'Porcelain Dinner Set 16-Piece',
    slug: 'porcelain-dinner-set-16-piece',
    description: 'Elegant white porcelain dinner set. Service for 4. Includes dinner plates, salad plates, bowls, and mugs. Microwave and dishwasher safe.',
    categorySlug: 'dinner-sets',
    price: 89.99,
    comparePrice: 129.99,
    costPrice: 53.99,
    stock: 45,
    sku: 'YW-TW-DS16',
    hsCode: '6911.10.0000',
    weightKg: 7.5,
    material: 'Porcelain',
    brand: 'YIWU',
    isFeatured: true,
  },
  {
    name: 'Stainless Steel Mixing Bowls Set of 3',
    slug: 'stainless-steel-mixing-bowls-set-of-3',
    description: 'Nesting mixing bowls in 3 sizes. Mirror-polished finish. Non-slip silicone bases. Dishwasher safe. Includes 1.5qt, 3qt, and 5qt.',
    categorySlug: 'bowls-plates',
    price: 26.99,
    comparePrice: 36.99,
    costPrice: 16.19,
    stock: 120,
    sku: 'YW-TW-MB3',
    hsCode: '7323.93.0000',
    weightKg: 1.8,
    material: 'Stainless Steel',
    brand: 'ChefPro',
  },
  {
    name: 'Ceramic Coffee Mug Set 4-Piece',
    slug: 'ceramic-coffee-mug-set-4-piece',
    description: 'Large 14oz coffee mugs. Ergonomic handles. Microwave and dishwasher safe. Available in multiple colors. Gift box packaging.',
    categorySlug: 'cups-mugs',
    price: 24.99,
    comparePrice: 34.99,
    costPrice: 14.99,
    stock: 160,
    sku: 'YW-TW-CM4',
    hsCode: '6912.00.0000',
    weightKg: 2.1,
    material: 'Ceramic',
    brand: 'KitchenMaster',
  },
]

// Helper function to generate tiered prices
export function generateTieredPrices(basePrice: number) {
  return [
    { minQuantity: 1, maxQuantity: 9, price: basePrice },
    { minQuantity: 10, maxQuantity: 49, price: Number((basePrice * 0.9).toFixed(2)) },
    { minQuantity: 50, maxQuantity: 99, price: Number((basePrice * 0.8).toFixed(2)) },
    { minQuantity: 100, maxQuantity: null, price: Number((basePrice * 0.7).toFixed(2)) },
  ]
}

// Helper function to generate variants
export function generateProductVariants(basePrice: number, productSku: string) {
  const colors = ['Black', 'Silver', 'Red', 'Blue']
  const sizes = ['Small', 'Medium', 'Large']
  
  return [
    {
      sku: `${productSku}-BLK-S`,
      attributes: { Color: 'Black', Size: 'Small' },
      price: Number((basePrice * 0.9).toFixed(2)),
      comparePrice: Number((basePrice * 1.1).toFixed(2)),
      stock: 50,
      isActive: true,
    },
    {
      sku: `${productSku}-SLV-M`,
      attributes: { Color: 'Silver', Size: 'Medium' },
      price: basePrice,
      comparePrice: Number((basePrice * 1.2).toFixed(2)),
      stock: 75,
      isActive: true,
    },
    {
      sku: `${productSku}-RED-L`,
      attributes: { Color: 'Red', Size: 'Large' },
      price: Number((basePrice * 1.1).toFixed(2)),
      comparePrice: Number((basePrice * 1.3).toFixed(2)),
      stock: 60,
      isActive: true,
    },
  ]
}
