export const ORDER_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PAID: 'PAID',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  IN_TRANSIT: 'IN_TRANSIT',
  CUSTOMS_HOLD: 'CUSTOMS_HOLD',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const

export const PAYMENT_STATUSES = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
} as const

export const SHIPPING_METHODS = {
  AIR_EXPRESS: 'AIR_EXPRESS',
  AIR_FREIGHT: 'AIR_FREIGHT',
  SEA_FREIGHT: 'SEA_FREIGHT',
  RAIL_FREIGHT: 'RAIL_FREIGHT',
  LAND_TRANSPORT: 'LAND_TRANSPORT',
} as const
