ALTER TABLE "contact_locations"
DROP COLUMN "displayOrder",
DROP COLUMN "map_url",
DROP COLUMN "name",
ADD COLUMN "city" TEXT NOT NULL,
ADD COLUMN "hours" TEXT,
ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "type" TEXT NOT NULL DEFAULT 'HUB',
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "isActive" SET NOT NULL,
ALTER COLUMN "createdAt" SET NOT NULL,
ALTER COLUMN "updatedAt" SET NOT NULL,
ALTER COLUMN "updatedAt" DROP DEFAULT;
