ALTER TABLE "contact_locations"
DROP COLUMN IF EXISTS "displayOrder",
DROP COLUMN IF EXISTS "map_url",
DROP COLUMN IF EXISTS "name",
ADD COLUMN IF NOT EXISTS "city" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "hours" TEXT,
ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'HUB',
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "isActive" SET NOT NULL,
ALTER COLUMN "createdAt" SET NOT NULL,
ALTER COLUMN "updatedAt" SET NOT NULL,
ALTER COLUMN "updatedAt" DROP DEFAULT;
