-- Update SystemSettings with sample contact and social media data
-- This script can be run in pgAdmin or any PostgreSQL client

-- First, check if any SystemSettings record exists
INSERT INTO system_settings (
  "companyName",
  "companyAddress", 
  "companyPhone",
  "companyEmail",
  "companyWebsite",
  "businessLicense",
  "taxRegistrationNumber",
  "companyDescription",
  "companyLogo",
  "companyLogoHeight",
  "primaryColor",
  "accentColor",
  "currency",
  "timezone",
  "language",
  "storeMode",
  "facebookUrl",
  "twitterUrl",
  "linkedinUrl",
  "instagramUrl",
  "wechatId",
  "whatsappNumber",
  "createdAt",
  "updatedAt"
) VALUES (
  'Global Trade Express',
  'Floor 15, International Trade Building, 123 Yiwu Commerce City, Zhejiang Province, China',
  '+86 579 8555 9999',
  'info@globaltradeexpress.com',
  'https://globaltradeexpress.com',
  'CHN-GTE-2024-001',
  '91330782MA2BQXXX88',
  'Leading international trade and logistics company connecting global businesses with Chinese manufacturers and suppliers.',
  '/images/logo.png',
  50,
  '#1a3a5c',
  '#c9a84c',
  'USD',
  'Asia/Shanghai',
  'en',
  'WHOLESALE',
  'https://facebook.com/globaltradeexpress',
  'https://twitter.com/GlobalTradeExp',
  'https://linkedin.com/company/global-trade-express',
  'https://instagram.com/globaltradeexpress',
  'GlobalTrade_CN',
  '+8613901234567',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  "companyName" = EXCLUDED."companyName",
  "companyAddress" = EXCLUDED."companyAddress",
  "companyPhone" = EXCLUDED."companyPhone", 
  "companyEmail" = EXCLUDED."companyEmail",
  "companyWebsite" = EXCLUDED."companyWebsite",
  "facebookUrl" = EXCLUDED."facebookUrl",
  "twitterUrl" = EXCLUDED."twitterUrl",
  "linkedinUrl" = EXCLUDED."linkedinUrl",
  "instagramUrl" = EXCLUDED."instagramUrl",
  "wechatId" = EXCLUDED."wechatId",
  "whatsappNumber" = EXCLUDED."whatsappNumber",
  "updatedAt" = NOW();