export const reusableSchemas = {
  ApiResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      data: { type: 'object' },
      error: { type: 'string', example: null },
      message: { type: 'string' },
    },
    required: ['success'],
  },
  ApiError: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: false },
      error: { type: 'string', example: 'Resource not found' },
      code: { type: 'string', example: 'NOT_FOUND' },
      statusCode: { type: 'number', example: 404 },
    },
    required: ['success', 'error'],
  },
  User: {
    type: 'object',
    properties: {
      id: { type: 'string', example: 'usr_clh89234892' },
      email: { type: 'string', format: 'email', example: 'buyer@example.com' },
      name: { type: 'string', example: 'Jane Doe' },
      role: { type: 'string', enum: ['USER', 'CUSTOMER', 'ADMIN', 'SUPPLIER'], example: 'USER' },
      companyName: { type: 'string', example: 'Global Trading Ltd' },
      phone: { type: 'string', example: '+1-555-0199' },
      country: { type: 'string', example: 'United States' },
      isActive: { type: 'boolean', example: true },
      isVerified: { type: 'boolean', example: true },
    },
    required: ['id', 'email', 'name', 'role'],
  },
  Product: {
    type: 'object',
    properties: {
      id: { type: 'string', example: 'prod_9082348923' },
      sku: { type: 'string', example: 'SKU-CHINA-001' },
      name: { type: 'string', example: 'Automatic Bag Sealing Machine' },
      slug: { type: 'string', example: 'automatic-bag-sealing-machine' },
      description: { type: 'string', example: 'Industrial packaging machine with temperature control' },
      price: { type: 'number', example: 450.0 },
      compareAtPrice: { type: 'number', example: 520.0 },
      wholesalePrice: { type: 'number', example: 380.0 },
      stock: { type: 'integer', example: 120 },
      weightKg: { type: 'number', example: 12.5 },
      images: {
        type: 'array',
        items: { type: 'string', format: 'uri' },
        example: ['https://yiwuexpress.com/images/machine1.jpg'],
      },
      countryOfOrigin: { type: 'string', example: 'China' },
      isActive: { type: 'boolean', example: true },
      minOrderQty: { type: 'integer', example: 1 },
    },
    required: ['id', 'sku', 'name', 'slug', 'price', 'stock'],
  },
  Category: {
    type: 'object',
    properties: {
      id: { type: 'string', example: 'cat_34823904' },
      name: { type: 'string', example: 'Industrial Machinery' },
      slug: { type: 'string', example: 'industrial-machinery' },
      description: { type: 'string', example: 'Heavy tools and packaging equipment' },
      parentId: { type: 'string', nullable: true, example: null },
      level: { type: 'integer', example: 1 },
      isActive: { type: 'boolean', example: true },
    },
    required: ['id', 'name', 'slug'],
  },
  CartItem: {
    type: 'object',
    properties: {
      id: { type: 'string', example: 'item_1234' },
      productId: { type: 'string', example: 'prod_9082348923' },
      quantity: { type: 'integer', example: 3 },
      product: { $ref: '#/components/schemas/Product' },
    },
    required: ['id', 'productId', 'quantity'],
  },
  Cart: {
    type: 'object',
    properties: {
      id: { type: 'string', example: 'cart_8923' },
      userId: { type: 'string', example: 'usr_clh89234892' },
      items: {
        type: 'array',
        items: { $ref: '#/components/schemas/CartItem' },
      },
      summary: {
        type: 'object',
        properties: {
          itemCount: { type: 'integer', example: 1 },
          totalQuantity: { type: 'integer', example: 3 },
          subtotal: { type: 'number', example: 1350.0 },
          totalWeight: { type: 'number', example: 37.5 },
        },
      },
    },
  },
  Order: {
    type: 'object',
    properties: {
      id: { type: 'string', example: 'ord_9823490' },
      orderNumber: { type: 'string', example: 'ORD-2026-90218' },
      userId: { type: 'string', example: 'usr_clh89234892' },
      customerName: { type: 'string', example: 'Jane Doe' },
      customerEmail: { type: 'string', format: 'email', example: 'buyer@example.com' },
      status: {
        type: 'string',
        enum: ['PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'],
        example: 'PENDING',
      },
      paymentStatus: {
        type: 'string',
        enum: ['UNPAID', 'PAID', 'FAILED', 'REFUNDED'],
        example: 'UNPAID',
      },
      subtotal: { type: 'number', example: 1350.0 },
      shippingFee: { type: 'number', example: 85.0 },
      tax: { type: 'number', example: 67.5 },
      total: { type: 'number', example: 1502.5 },
      currency: { type: 'string', example: 'USD' },
    },
    required: ['id', 'orderNumber', 'status', 'total'],
  },
  WholesaleQuote: {
    type: 'object',
    properties: {
      id: { type: 'string', example: 'quote_98234' },
      inquiryNumber: { type: 'string', example: 'INQ-2026-4432' },
      companyName: { type: 'string', example: 'Global Supply Corp' },
      status: {
        type: 'string',
        enum: ['PENDING', 'UNDER_REVIEW', 'QUOTED', 'ACCEPTED', 'REJECTED'],
        example: 'PENDING',
      },
      estimatedOrderValue: { type: 'number', example: 15000.0 },
    },
  },
  SystemSettings: {
    type: 'object',
    properties: {
      companyName: { type: 'string', example: 'Global Trade' },
      primaryColor: { type: 'string', example: '#1a3a5c' },
      accentColor: { type: 'string', example: '#c9a84c' },
      currency: { type: 'string', example: 'USD' },
      storeMode: { type: 'string', enum: ['WHOLESALE', 'RETAIL', 'BOTH'], example: 'WHOLESALE' },
    },
  },
}
